language: python
sudo: false
python:
  - "3.6"

env:
  - TOX_ENV=quality
  - TOX_ENV=py27-18
  - TOX_ENV=py27-19
  - TOX_ENV=py27-110
  - TOX_ENV=py27-111
  - TOX_ENV=py34-18
  - TOX_ENV=py34-19
  - TOX_ENV=py34-110
  - TOX_ENV=py34-111
  - TOX_ENV=py36-111
# Because python3.5 image in Travis behaves weird we need to add python 3.5 runs explicitly to the matrix
matrix:
    include:
      - python: 3.5
        env:
          - TOX_ENV=py35-18
      - python: 3.5
        env:
          - TOX_ENV=py35-19
      - python: 3.5
        env:
          - TOX_ENV=py35-110
      - python: 3.5
        env:
          - TOX_ENV=py35-111
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
